#include "host.h"
#include "exposeval.h"   /* generated by kama: every struct below is kama's declaration, published */

int host_run(void) {
    FrameStats s = exposeval_makeStats(10);                    /* built in kama, read in C */
    if (s.origin.x != 3.0f || s.kind != exposeval_geo_Kind_Segment || s.tag.v[2] != 3) return 100;
    s.frames = 20;                                             /* changed in C, read back in kama */
    exposeval_geo_Vec2 v = { 1.0f, 2.0f };
    exposeval_Wire w = { 2, 40 };
    if (sizeof(exposeval_Wire) != 5) return 101;               /* `@packed` reached the host */
    return exposeval_readStats(s)                              /* 20 + 25 + 2 + 3 = 50 */
         + (int)exposeval_geo_lengthSq(v)                      /* 5 */
         + (int)exposeval_wireArg(w);                          /* 42 */
}
