/* Generated by cstar. Do not edit. */
#include "cstar_runtime.h"

typedef struct _F1__Move _F1__Move;
typedef struct _F1__C__F1__Move _F1__C__F1__Move;
typedef struct Copyable_vtbl Copyable_vtbl;
typedef struct Copyable Copyable;
typedef struct Movable_vtbl Movable_vtbl;
typedef struct Movable Movable;

struct _F1__Move {
    int32_t n;
};

struct _F1__C__F1__Move {
    _F1__Move x;
};

struct Copyable_vtbl {
    Copyable (*copy)(void* self);
    void (*__dtor)(void*);
};
struct Copyable { void* obj; const Copyable_vtbl* vtbl; };

struct Movable_vtbl {
    void (*__dtor)(void*);
};
struct Movable { void* obj; const Movable_vtbl* vtbl; };

void _F1__Move__dtor(_F1__Move* self);
void _F1__Move__ctor(_F1__Move* self, int32_t n);
void _F1__Move__dtor(_F1__Move* self);
int32_t _F1__Move__get(_F1__Move* self);
static inline void _F1__C__F1__Move__ctor(_F1__C__F1__Move* self, _F1__Move v);
static inline void _F1__C__F1__Move__dtor(_F1__C__F1__Move* self);
static inline _F1__C__F1__Move _F1__C__F1__Move__copy(_F1__C__F1__Move* self);
int32_t cstar_main(void);

#line 6 "/work/_copytest.cstar"
static inline void _F1__C__F1__Move__ctor(_F1__C__F1__Move* self, _F1__Move v)
{
#line 6 "/work/_copytest.cstar"
    _F1__Move__dtor(&self->x);
    self->x = v;
}

#line 7 "/work/_copytest.cstar"
static inline _F1__C__F1__Move _F1__C__F1__Move__copy(_F1__C__F1__Move* self)
{
#line 7 "/work/_copytest.cstar"
/* TODO(cstar): unsupported `_F1__Move` has no `copy` method — add one to opt into `Copyable`, or use `give` to move it */    _F1__C__F1__Move __ctorarg1; _F1__C__F1__Move__ctor(&__ctorarg1, _F1__Move__copy(&(self->x)));
    _F1__C__F1__Move __ret_0 = __ctorarg1;
    return __ret_0;
}

#line 8 "/work/_copytest.cstar"
static inline void _F1__C__F1__Move__dtor(_F1__C__F1__Move* self)
{
    _F1__Move__dtor(&self->x);
}

#line 3 "/work/_copytest.cstar"
void _F1__Move__ctor(_F1__Move* self, int32_t n)
{
#line 3 "/work/_copytest.cstar"
    (self->n = n);
}

#line 3 "/work/_copytest.cstar"
int32_t _F1__Move__get(_F1__Move* self)
{
#line 3 "/work/_copytest.cstar"
    int32_t __ret_0 = self->n;
    return __ret_0;
}

#line 3 "/work/_copytest.cstar"
void _F1__Move__dtor(_F1__Move* self)
{
}

#line 14 "/work/_copytest.cstar"
int32_t cstar_main(void)
{
#line 11 "/work/_copytest.cstar"
    _F1__Move m;
#line 11 "/work/_copytest.cstar"
    _F1__Move__ctor(&m, 5);
#line 12 "/work/_copytest.cstar"
    _F1__C__F1__Move c;
#line 12 "/work/_copytest.cstar"
    _F1__C__F1__Move__ctor(&c, m);
#line 13 "/work/_copytest.cstar"
/* TODO(cstar): unsupported method call on unresolved receiver */    int32_t __ret_0 = 0;
    _F1__C__F1__Move__dtor(&c);
    return __ret_0;
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    return (int)cstar_main();
}

