#include "rgb.h"
#include "hosthdr.h"   /* generated by kama — nothing below declares a kama symbol or type by hand */

static int32_t twice(int32_t x) { return x * 2; }

int host_run(void) {
    int32_t data[3] = { 1, 2, 3 };
    std_collections_ConstView_int32 view = { data, 3 };
    kama_InlineArray_int32_4 four = { { 1, 2, 3, 4 } };
    Rgb c = { 1, 7, 3 };
    hosthdr_Op f = twice;
    hosthdr_shapes_Shape* opaque = 0;   /* nameable, not constructible: its layout is kama's */
    return (hosthdr_shapes_known(opaque) ? 1000 : 0)                                /*  0 */
         + hosthdr_apply(f, 5)                                                      /* 10 */
         + hosthdr_sumFour(four)                                                    /* 10 */
         + hosthdr_sumView(view)                                                    /*  6 */
         + hosthdr_green(c)                                                         /*  7 */
         + host_visible_answer()                                                    /* 42 */
         + (hosthdr_shapes_classify(2) == hosthdr_shapes_Kind_Square ? 4 : 1000);   /*  4 */
}
