<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>bench</AssemblyName>
    <Optimize>true</Optimize>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
