#include "fmt.h"
#include "externenum.h"   /* generated by kama: `externenum_pick`, which takes and returns the C enum */
int32_t fmt_bits(Format f)       { return f == FORMAT_UNDEFINED ? 0 : 32; }
int32_t surface_score(Surface s) { return s.width + (int32_t)s.format; }
int32_t host_calls(void)         { return externenum_pick(FORMAT_RGBA8) == FORMAT_BGRA8 ? 5 : 900; }
