#include "level.h"
#include "boundenum.h"   /* generated by kama: `boundenum_weigh`, `boundenum_flip`, `boundenum_Level` */
int32_t mode_raw(Mode m) { return (int32_t)m; }
int32_t host_run(void) {
    return boundenum_weigh(boundenum_Level_High)                   /* 20: a kama method, reached from C */
         + (boundenum_flip(MODE_OFF) == MODE_ON ? 3 : 900);        /*  3 */
}
