#!/bin/sh
# check-unicode.sh — std::unicode's normalization agrees with the Unicode Character Database, line for line.
#
# include/kama_unicode.h is GENERATED (tools/gen-unicode, from one pinned UCD version), and the UCD ships its own
# answer key: NormalizationTest.txt, where every line is five strings and UAX #15 says what each of NFC, NFD, NFKC and
# NFKD must make of each — about 20,000 lines, plus the rule that every code point Part 1 does not list is left
# alone by all four. tests/support/unicode_conform.c applies every one of those checks (4.7 million) to the header,
# reading the same version's test file, which gen-unicode stores gzipped beside it. A table built wrong, an
# algorithm step out of order, a Hangul edge — each is a failure here with the line that shows it.
#
# The C compiler only — no kama build — so it is fast and says nothing about the kama wrapper, which
# tests/unicode_normalize.kama covers.
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
CC=${CC:-cc}
if ! command -v "$CC" >/dev/null 2>&1; then
    echo "SKIP check-unicode (no C compiler on PATH)"
    exit 0
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

if ! "$CC" -std=c11 -O2 -I "$ROOT/include" "$ROOT/tests/support/unicode_conform.c" -o "$tmp/conform" 2> "$tmp/cc"; then
    echo "check-unicode: FAIL — the conformance harness does not compile against include/kama_unicode.h:" >&2
    sed 's/^/    /' "$tmp/cc" | head -8 >&2
    exit 1
fi
gunzip -c "$ROOT/tests/support/NormalizationTest.txt.gz" > "$tmp/NormalizationTest.txt"
# A test file that is not the version the header was generated from proves nothing about it.
want=$(sed -n 's/^\/\* GENERATED by tools\/gen-unicode from the Unicode Character Database \([0-9.]*\).*/\1/p' "$ROOT/include/kama_unicode.h")
have=$(sed -n '1s/^# NormalizationTest-\([0-9.]*\)\.txt.*/\1/p' "$tmp/NormalizationTest.txt")
if [ -z "$want" ] || [ "$want" != "$have" ]; then
    echo "check-unicode: FAIL — the header is Unicode '$want' and the test data '$have'; regenerate both (tools/gen-unicode)" >&2
    exit 1
fi
if ! "$tmp/conform" < "$tmp/NormalizationTest.txt" > "$tmp/out" 2>&1; then
    echo "check-unicode: FAIL — normalization disagrees with the UCD's NormalizationTest.txt ($want):" >&2
    sed 's/^/    /' "$tmp/out" | head -12 >&2
    exit 1
fi
echo "check-unicode: PASS (Unicode $want: $(cat "$tmp/out"))"
