#!/bin/sh
# Embed the built-in kama sources into a generated C++ translation unit, so the language core
# ships inside bin/kama and survives a `--no-std` install (see install.sh, kama.prelude.h).
#
#   usage: embed_prelude.sh OUT GLOBAL MODULE...
#
# GLOBAL is the empty-namespace prelude (prelude/global.kama); each MODULE is a namespaced built-in
# unit (prelude/std/memory/*.kama). Each source is wrapped in a C++11 raw string literal with the
# KAMASRC delimiter — kama source never contains `)KAMASRC"`, so no escaping is needed.
set -eu

out=$1; shift
global=$1; shift

{
  printf '// GENERATED by tools/embed_prelude.sh — do not edit. Regenerated from prelude/*.kama.\n'
  printf '#include "kama.prelude.h"\n\n'

  # No `extern` on the definitions: kama.prelude.h (included above) already declares them extern, so
  # these get external linkage from that prior declaration — and without the -Wextern-initializer warning.
  printf 'const char* KAMA_PRELUDE_SRC =\n'
  printf 'R"KAMASRC(\n'
  cat "$global"
  printf ')KAMASRC";\n\n'

  printf 'const KamaPreludeModule KAMA_PRELUDE_MODULES[] = {\n'
  n=0
  for m in "$@"; do
    printf '  { R"KAMASRC(\n'
    cat "$m"
    printf ')KAMASRC" },\n'
    n=$((n + 1))
  done
  printf '};\n'
  printf 'const int KAMA_PRELUDE_MODULE_COUNT = %d;\n' "$n"
} > "$out"
