#!/bin/sh
# Embed the agent-guidance files into a generated C++ translation unit, so `kama agents` works from
# any install — including `--no-std`, which ships only bin/kama (see install.sh, kama.agents.h).
#
#   usage: embed_agents.sh OUT AGENTS SKILL PACKAGE STUB...
#
# AGENTS is agents/AGENTS.md (the content, once). SKILL is the richer on-demand cookbook. PACKAGE is
# the addendum a `kind: library` project gets beside AGENTS.md (agents/PACKAGE.md). Each STUB is
# a per-tool POINTER file, named for the tool it serves: the basename before `.md` becomes the key
# `kama agents --tool <key>` takes, so adding a tool is a new file plus a Makefile entry, and touches
# no C++.
#
# Markdown can legally contain any byte sequence, so unlike the prelude (whose kama source never
# contains the delimiter) the raw-string delimiter here has to be one no document would type.
set -eu

out=$1; shift
agents=$1; shift
skill=$1; shift
package=$1; shift

# The fixture markers are REPO metadata and do not travel. `check-doc-claims.sh` requires every "the
# compiler rejects this" sentence in agents/AGENTS.md to name the `tests/xfail/` fixture that proves it —
# which is what keeps this file honest, and is there because three of its claims had gone stale unnoticed.
# But the file is INSTALLED into other people's projects, where `tests/xfail/foreach_char_over_string`
# names nothing. So the marker is stripped on the way in, exactly as a stub's `dest:` line is: the source
# carries the proof, the installed copy carries the claim. `check-agents.sh` asserts the two match under
# the same strip, so the DRY property is still exact rather than approximate.
strip_markers() { sed -E 's/[[:space:]]*<!-- *(xfail|test): *[^>]*-->//g' "$1"; }

# A stub declares its own destination on line 1 as `<!-- dest: <path> -->`; that line is stripped from
# the emitted text, so what lands in the project is only the pointer.
emit() {   # emit <name> <file>
  dest=$(sed -n '1s/^<!-- *dest: *\(.*[^ ]\) *-->$/\1/p' "$2")
  if [ -z "$dest" ]; then
    echo "embed_agents: $2 line 1 must be '<!-- dest: <path> -->'" >&2
    exit 1
  fi
  printf '  { "%s", "%s", R"KAMAGENTS(\n' "$1" "$dest"
  sed '1d' "$2" | sed -E 's/[[:space:]]*<!-- *(xfail|test): *[^>]*-->//g'
  printf ')KAMAGENTS" },\n'
}

for f in "$agents" "$skill" "$package" "$@"; do
  if grep -q ')KAMAGENTS"' "$f"; then
    echo "embed_agents: $f contains the raw-string delimiter — rename it" >&2
    exit 1
  fi
done

{
  printf '// GENERATED by tools/embed_agents.sh — do not edit. Regenerated from agents/.\n'
  printf '#include "kama.agents.h"\n\n'

  printf 'const char* KAMA_AGENTS_MD =\n'
  printf 'R"KAMAGENTS(\n'
  strip_markers "$agents"
  printf ')KAMAGENTS";\n\n'

  printf 'const char* KAMA_AGENTS_SKILL =\n'
  printf 'R"KAMAGENTS(\n'
  strip_markers "$skill"
  printf ')KAMAGENTS";\n\n'

  printf 'const char* KAMA_AGENTS_PACKAGE =\n'
  printf 'R"KAMAGENTS(\n'
  strip_markers "$package"
  printf ')KAMAGENTS";\n\n'

  printf 'const KamaAgentStub KAMA_AGENT_STUBS[] = {\n'
  n=0
  for s in "$@"; do
    name=$(basename "$s" .md)
    emit "$name" "$s"
    n=$((n + 1))
  done
  printf '};\n'
  printf 'const int KAMA_AGENT_STUB_COUNT = %d;\n' "$n"
} > "$out"
